# Generated by Django 5.1.15 on 2026-09-30 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Consultation', max_length=255)),
                ('mode', models.CharField(choices=[('guideline_qa', 'Guideline Q&A'), ('clinical_note_qa', 'Clinical Note Q&A'), ('study_mode', 'Study & Quiz Mode')], default='guideline_qa', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, help_text='Aggregated rerank/faithfulness score (0.0 to 1.0)', null=True)),
                ('is_not_found', models.BooleanField(default=False, help_text="True if confidence gate triggered 'not found in sources'.")),
                ('disclaimer', models.TextField(default='DISCLAIMER: ClinSaarthi AI is an educational clinical knowledge assistant designed to support medical research and guideline review. It does NOT provide formal medical advice, definitive diagnoses, or binding treatment prescriptions. All recommendations must be evaluated and confirmed by licensed healthcare professionals.', help_text='Mandatory clinical disclaimer displayed on every answer.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='qa.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_index', models.PositiveSmallIntegerField(help_text='Citation index number: 1, 2, 3')),
                ('inline_tag', models.CharField(help_text='e.g. [1], [2]', max_length=10)),
                ('source_title', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('highlight_text', models.TextField(help_text='Exact sentence or passage cited from source')),
                ('bounding_box', models.JSONField(blank=True, default=dict)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='documents.chunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='qa.message')),
            ],
            options={
                'ordering': ['citation_index'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=120)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('route', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified in Source'), ('UNSUPPORTED', 'Unsupported by Source'), ('CONFLICT', 'Direct Conflict / Contradiction')], max_length=20)),
                ('nli_score', models.FloatField(blank=True, help_text='NLI entailment confidence score', null=True)),
                ('explanation', models.TextField(blank=True)),
                ('rxnorm_cui', models.CharField(blank=True, help_text='RxNorm Concept Unique Identifier', max_length=64)),
                ('openfda_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='qa.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
