# Generated by Django 5.1.15 on 2026-09-30 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_sets', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField(help_text='Clinical question, symptom cluster, or drug name')),
                ('back', models.TextField(help_text='Mechanism, guideline recommendation, dosage, or contraindication')),
                ('key_concept', models.CharField(blank=True, max_length=150)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.flashcardset')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('difficulty', models.CharField(choices=[('EASY', 'Basic Terminology & Concepts'), ('MEDIUM', 'Clinical Scenarios & Guidelines'), ('HARD', 'Complex Pharmacology & Differential Diagnosis')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option_index', models.PositiveSmallIntegerField(help_text='0-indexed pointer to correct option')),
                ('explanation', models.TextField(blank=True, help_text='Clinical justification grounded in source text')),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.quiz')),
            ],
        ),
    ]
