# Generated by Django 5.1.15 on 2026-10-01 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='flashcardset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='Difficulty multiplier (minimum 1.3)'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval_days',
            field=models.PositiveIntegerField(default=1, help_text='Days until next review'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive successful recalls'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='topic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('QUIZ', 'Multiple Choice Quiz'), ('FLASHCARD', 'Flashcard SRS Review')], default='QUIZ', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('correct_items', models.PositiveIntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='study.flashcardset')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='study.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
