# Generated by Django 5.1.15 on 2026-09-30 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Clinical Note', max_length=255)),
                ('masked_content', models.TextField(help_text='Sanitized note text with placeholders (e.g. [PATIENT_1], [PHONE_1]).')),
                ('pii_entity_count', models.PositiveIntegerField(default=0, help_text='Number of detected and masked PII entities.')),
                ('department', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIIMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_data', models.JSONField(default=dict, help_text='Secure mapping dictionary from placeholder token to original value.')),
                ('categories_detected', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pii_mapping', to='notes.clinicalnote')),
            ],
        ),
    ]
