# Generated by Django 5.1.15 on 2026-09-30 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='guidelines/')),
                ('description', models.TextField(blank=True)),
                ('author_or_source', models.CharField(blank=True, help_text='e.g. WHO, AHA, ESC, NICE', max_length=255)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(db_index=True)),
                ('page_number', models.PositiveIntegerField(db_index=True, help_text='1-based PDF page number')),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(help_text='Exact text segment used for retrieval')),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('bounding_box', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'page_number', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Extracting Layout & Columns'), ('CHUNKING', 'Sentence-Aware Chunking'), ('EMBEDDING', 'Generating Embeddings & Storing'), ('COMPLETED', 'Ingestion Completed'), ('FAILED', 'Ingestion Failed')], default='PENDING', max_length=30)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('chunks_created', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_jobs', to='documents.document')),
            ],
        ),
    ]
